spring:
  profiles:
        active: local
#        active: prod

---

spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/xymm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1QAZ2wsx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: test
  jpa:
    database: HSQL